version: '3.8'

services:
  dashboard:
    image: ${DOCKERHUB_USERNAME}/price-tracker-dashboard:latest
    container_name: price-tracker-dashboard
    ports:
      - "8501:8501"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - API_URL=http://price-tracker-api:8000

  price-tracker-api:
    image: ${DOCKERHUB_USERNAME}/price-tracker-api:latest
    container_name: price-tracker-api
    ports:
      - "8000:8000"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
