version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-le
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=florian.gallardo@email.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh

  dashboard:
    image: ${DOCKERHUB_USERNAME}/price-tracker-dashboard:latest
    container_name: price-tracker-dashboard
    restart: always
    ports:
      - "8501:8501"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - API_URL=https://api-price-tracker.duckdns.org
      - VIRTUAL_HOST=price-tracker.duckdns.org
      - LETSENCRYPT_HOST=price-tracker.duckdns.org
      - LETSENCRYPT_EMAIL=florian.gallardo@email.com

  price-tracker-api:
    image: ${DOCKERHUB_USERNAME}/price-tracker-api:latest
    container_name: price-tracker-api
    ports:
      - "8000:8000"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
