name: Build and Deploy Dashboard

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image Dashboard
        uses: docker/build-push-action@v5
        with:
          context: .
          files: ./Dockerfile.dashboard
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/price-tracker-dashboard:latest

      - name: Build and push Docker image API
        uses: docker/build-push-action@v5
        with:
          context: .
          files: ./Dockerfile.api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/price-tracker-api:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/price-tracker-dashboard:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/price-tracker-api:latest

            docker stop price-tracker-api || true
            docker stop price-tracker-dashboard || true

            docker rm price-tracker-api || true
            docker rm price-tracker-dashboard || true
            docker run -d \
              --name price-tracker-dashboard \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e AWS_DEFAULT_REGION=eu-west-3 \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_NAME=db-prices \
              -e API_URL=http://localhost:8000 \
              -p 8501:8501 \
              ${{ secrets.DOCKERHUB_USERNAME }}/price-tracker-dashboard:latest

            docker run -d \
              --name price-tracker-api \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e AWS_DEFAULT_REGION=eu-west-3 \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_NAME=db-prices \
              -p 8000:8000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/price-tracker-api:latest